name: Website - Production # name of your workflow
on:
  push:
    branches:
      - production # Deployment will be triggered when we will push to the master branch
jobs:
  build:
    name: Build & Deploy # name of the job
    runs-on: ubuntu-latest # the runner in which the job will be executed
    steps:
      - uses: actions/checkout@v3
        with:
          ref: refs/heads/production
          path: public
      - uses: google-github-actions/auth@v0
        with:
          service_account: '${{ secrets.GCP_SA_EMAIL }}'
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
      - uses: google-github-actions/setup-gcloud@v0
      - run: gsutil -m rsync -x "gha-creds.*\.json$|^.*\.git.*$|.*\.github.*$" -d -c -r public/ gs://devopsand.coffee
        #comment
